"use client";

import { Icons } from "../icons";

export const INITIAL_CUSTOM_ITEMS = [

  // ════════════════════════════════════════════════════════════════════════════
  // C:\ — Top-level folders
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: "folder-windows",
    title: "JacobOS",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "drive-c",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 8,
  },
  {
    id: "folder-program-files",
    title: "Program Files",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "drive-c",
    createdAt: Date.parse("2026-01-10T08:01:00"),
    sortOrder: 9,
  },
  {
    id: "folder-users",
    title: "Users",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "drive-c",
    createdAt: Date.parse("2026-01-10T08:02:00"),
    sortOrder: 10,
  },
  {
    id: "folder-projects",
    title: "Projects",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "drive-c",
    createdAt: Date.parse("2026-01-10T08:03:00"),
    sortOrder: 11,
  },
  {
    id: "folder-temp",
    title: "Temp",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "drive-c",
    createdAt: Date.parse("2026-01-10T08:04:00"),
    sortOrder: 12,
  },

  // ════════════════════════════════════════════════════════════════════════════
  // C:\ — Root files
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: "text-readme",
    title: "readme.txt",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "drive-c",
    createdAt: Date.parse("2026-01-10T08:55:00"),
    sortOrder: 20,
    content:
      "JacobOS v1.0 — Build 2026\n\nThis drive contains the JacobOS shell and all supporting files.\nDouble-click any app on the desktop to explore:\n\n  About        Resume-style bio\n  Skills       Technologies & tools\n  Experience   Work history\n  Projects     Shipped code & side projects\n  Contact      How to reach Jacob\n  Terminal     Command-line interface\n\nSystem files are in C:\\Windows\\System32\\\nInstalled apps are in C:\\Program Files\\\nUser files are in C:\\Users\\Jacob\\",
  },
  {
    id: "text-autoexec",
    title: "autoexec.bat",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "drive-c",
    createdAt: Date.parse("2026-01-10T09:00:00"),
    sortOrder: 21,
    content:
      "@echo off\nprompt $p$g\npath C:\\Windows;C:\\Windows\\System32;C:\\Program Files\\JacobOS\nset COMPUTERNAME=JACOB-PC\nset USERNAME=jacob\nset OS=JacobOS\nset VERSION=1.0\necho JacobOS initialized. Welcome, %USERNAME%.",
  },
  {
    id: "text-config",
    title: "config.sys",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "drive-c",
    createdAt: Date.parse("2026-01-10T09:03:00"),
    sortOrder: 22,
    content:
      "FILES=64\nBUFFERS=30\nDOS=HIGH,UMB\nSTACKS=9,256\n\n; JacobOS System Configuration\nDEVICE=C:\\Windows\\System32\\himem.sys\nDEVICE=C:\\Windows\\System32\\emm386.exe NOEMS\nDEVICEHIGH=C:\\Windows\\System32\\setver.exe",
  },

  // ════════════════════════════════════════════════════════════════════════════
  // C:\JacobOS\  (OS system directory)
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: "folder-system32",
    title: "System32",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "folder-windows",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 8,
  },
  {
    id: "folder-drivers",
    title: "Drivers",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "folder-windows",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 9,
  },
  {
    id: "folder-fonts",
    title: "Fonts",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "folder-windows",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 10,
  },
  {
    id: "folder-config",
    title: "Config",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "folder-windows",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 11,
  },
  {
    id: "text-system-log",
    title: "system.log",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-windows",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 20,
    content:
      "[2026-01-10 08:00:01] Boot initiated — JacobOS v1.0\n[2026-01-10 08:00:03] Memory check passed. 512 MB OK.\n[2026-01-10 08:00:05] Loading kernel — ntoskrnl.exe\n[2026-01-10 08:00:06] HAL initialized — hal.dll\n[2026-01-10 08:00:07] Shell loaded — explorer.exe\n[2026-01-10 08:00:09] All subsystems nominal. Desktop ready.\n[2026-01-14 09:00:00] Patch applied — hotfix-1.0.1\n[2026-03-13 12:00:00] Stable build confirmed — no critical errors.",
  },
  {
    id: "text-boot-log",
    title: "boot.log",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-windows",
    createdAt: Date.parse("2026-03-13T12:00:00"),
    sortOrder: 21,
    content:
      "JacobOS Boot Log — 2026-03-13\n\nLoaded: ntoskrnl.exe\nLoaded: hal.dll\nLoaded: System32\\kernel32.dll\nLoaded: System32\\user32.dll\nLoaded: System32\\gdi32.dll\nLoaded: System32\\shell32.dll\nLoaded: System32\\advapi32.dll\nLoaded: System32\\rpcrt4.dll\nLoaded: System32\\ole32.dll\nLoaded: System32\\ws2_32.dll\nLoaded: Drivers\\acpi.sys\nLoaded: Drivers\\pci.sys\nLoaded: Drivers\\disk.sys\nLoaded: Drivers\\ntfs.sys\nLoaded: Drivers\\tcpip.sys\n\nBoot completed in 3.2 seconds.",
  },
  {
    id: "binary-hal",
    title: "hal.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-windows",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 30,
  },
  {
    id: "binary-ntoskrnl",
    title: "ntoskrnl.exe",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-windows",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 31,
  },
  {
    id: "binary-explorer",
    title: "explorer.exe",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-windows",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 32,
  },
  {
    id: "binary-notepad",
    title: "notepad.exe",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-windows",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 33,
  },
  {
    id: "binary-calc",
    title: "calc.exe",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-windows",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 34,
  },

  // ── C:\JacobOS\Config\ ────────────────────────────────────────────────────
  {
    id: "text-jacobos-ini",
    title: "jacobos.ini",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-config",
    createdAt: Date.parse("2026-01-10T08:30:00"),
    sortOrder: 10,
    content:
      "[JacobOS]\nVersion=1.0\nBuild=2026-03-13\nComputerName=JACOB-PC\nUser=jacob\n\n[Desktop]\nWallpaper=(None)\nTileWallpaper=0\nColor=#008080\nIconSize=normal\n\n[Shell]\nClockFormat=12h\nBootAnimation=true\nSoundEnabled=true",
  },
  {
    id: "text-system-ini",
    title: "system.ini",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-config",
    createdAt: Date.parse("2026-01-10T08:30:00"),
    sortOrder: 11,
    content:
      "[boot]\nsystem.drv=system.drv\nshell=explorer.exe\nfailsafe.shell=explorer.exe\n\n[386Enh]\nwallpaper=(None)\n\n[drivers]\ntimer=timer.drv\nmidiMapper=midimap.drv",
  },
  {
    id: "binary-ntuser",
    title: "ntuser.dat",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-config",
    createdAt: Date.parse("2026-01-10T08:30:00"),
    sortOrder: 20,
  },
  {
    id: "binary-software-hive",
    title: "SOFTWARE",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-config",
    createdAt: Date.parse("2026-01-10T08:30:00"),
    sortOrder: 21,
  },
  {
    id: "binary-system-hive",
    title: "SYSTEM",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-config",
    createdAt: Date.parse("2026-01-10T08:30:00"),
    sortOrder: 22,
  },

  // ── C:\JacobOS\Drivers\ ───────────────────────────────────────────────────
  {
    id: "binary-acpi",
    title: "acpi.sys",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-drivers",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 10,
  },
  {
    id: "binary-pci",
    title: "pci.sys",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-drivers",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 11,
  },
  {
    id: "binary-disk-sys",
    title: "disk.sys",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-drivers",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 12,
  },
  {
    id: "binary-ntfs",
    title: "ntfs.sys",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-drivers",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 13,
  },
  {
    id: "binary-tcpip",
    title: "tcpip.sys",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-drivers",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 14,
  },
  {
    id: "binary-ndis",
    title: "ndis.sys",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-drivers",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 15,
  },
  {
    id: "binary-usbstor",
    title: "usbstor.sys",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-drivers",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 16,
  },
  {
    id: "binary-volmgr",
    title: "volmgr.sys",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-drivers",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 17,
  },
  {
    id: "binary-atapi",
    title: "atapi.sys",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-drivers",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 18,
  },
  {
    id: "binary-classpnp",
    title: "classpnp.sys",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-drivers",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 19,
  },
  {
    id: "binary-storport",
    title: "storport.sys",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-drivers",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 20,
  },
  {
    id: "binary-dxgkrnl",
    title: "dxgkrnl.sys",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-drivers",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 21,
  },
  {
    id: "binary-usbhub",
    title: "usbhub.sys",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-drivers",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 22,
  },
  {
    id: "binary-cdrom",
    title: "cdrom.sys",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-drivers",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 23,
  },

  // ── C:\JacobOS\System32\ ──────────────────────────────────────────────────
  {
    id: "binary-kernel32",
    title: "kernel32.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 10,
  },
  {
    id: "binary-ntdll",
    title: "ntdll.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 11,
  },
  {
    id: "binary-user32",
    title: "user32.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 12,
  },
  {
    id: "binary-gdi32",
    title: "gdi32.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 13,
  },
  {
    id: "binary-shell32",
    title: "shell32.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 14,
  },
  {
    id: "binary-advapi32",
    title: "advapi32.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 15,
  },
  {
    id: "binary-rpcrt4",
    title: "rpcrt4.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 16,
  },
  {
    id: "binary-ole32",
    title: "ole32.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 17,
  },
  {
    id: "binary-oleaut32",
    title: "oleaut32.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 18,
  },
  {
    id: "binary-comctl32",
    title: "comctl32.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 19,
  },
  {
    id: "binary-comdlg32",
    title: "comdlg32.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 20,
  },
  {
    id: "binary-msvcrt",
    title: "msvcrt.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 21,
  },
  {
    id: "binary-msvcp140",
    title: "msvcp140.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 22,
  },
  {
    id: "binary-vcruntime",
    title: "vcruntime140.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 23,
  },
  {
    id: "binary-ws2-32",
    title: "ws2_32.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 24,
  },
  {
    id: "binary-winhttp",
    title: "winhttp.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 25,
  },
  {
    id: "binary-wininet",
    title: "wininet.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 26,
  },
  {
    id: "binary-shlwapi",
    title: "shlwapi.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 27,
  },
  {
    id: "binary-crypt32",
    title: "crypt32.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 28,
  },
  {
    id: "binary-secur32",
    title: "secur32.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 29,
  },
  {
    id: "binary-wintrust",
    title: "wintrust.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 30,
  },
  {
    id: "binary-combase",
    title: "combase.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 31,
  },
  {
    id: "binary-psapi",
    title: "psapi.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 32,
  },
  {
    id: "binary-dbghelp",
    title: "dbghelp.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 33,
  },
  {
    id: "binary-imagehlp",
    title: "imagehlp.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 34,
  },
  {
    id: "binary-setupapi",
    title: "setupapi.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 35,
  },
  {
    id: "binary-version",
    title: "version.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 36,
  },
  {
    id: "binary-netapi32",
    title: "netapi32.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 37,
  },
  {
    id: "binary-urlmon",
    title: "urlmon.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 38,
  },
  {
    id: "binary-winmm",
    title: "winmm.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 39,
  },
  {
    id: "binary-winspool",
    title: "winspool.drv",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 40,
  },
  {
    id: "binary-cmd",
    title: "cmd.exe",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 50,
  },
  {
    id: "binary-svchost",
    title: "svchost.exe",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 51,
  },
  {
    id: "binary-taskmgr",
    title: "taskmgr.exe",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 52,
  },
  {
    id: "binary-regedit",
    title: "regedit.exe",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 53,
  },
  {
    id: "binary-msiexec",
    title: "msiexec.exe",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 54,
  },
  {
    id: "binary-services",
    title: "services.exe",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 55,
  },
  {
    id: "binary-lsass",
    title: "lsass.exe",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 56,
  },
  {
    id: "binary-winlogon",
    title: "winlogon.exe",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 57,
  },
  {
    id: "binary-rundll32",
    title: "rundll32.exe",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 58,
  },
  {
    id: "binary-regsvr32",
    title: "regsvr32.exe",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 59,
  },
  {
    id: "binary-conhost",
    title: "conhost.exe",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 60,
  },
  {
    id: "binary-ping",
    title: "ping.exe",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 61,
  },
  {
    id: "binary-net",
    title: "net.exe",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 62,
  },
  {
    id: "binary-ipconfig",
    title: "ipconfig.exe",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 63,
  },
  {
    id: "binary-attrib",
    title: "attrib.exe",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 64,
  },
  {
    id: "binary-xcopy",
    title: "xcopy.exe",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 65,
  },
  {
    id: "binary-himem",
    title: "himem.sys",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 70,
  },
  {
    id: "binary-mshtml",
    title: "mshtml.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-system32",
    createdAt: Date.parse("2026-01-10T08:00:00"),
    sortOrder: 41,
  },

  // ════════════════════════════════════════════════════════════════════════════
  // C:\Program Files\
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: "folder-jacobos-app",
    title: "JacobOS Shell",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "folder-program-files",
    createdAt: Date.parse("2026-01-10T09:00:00"),
    sortOrder: 8,
  },
  {
    id: "folder-vscode",
    title: "Visual Studio Code",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "folder-program-files",
    createdAt: Date.parse("2025-06-01T10:00:00"),
    sortOrder: 9,
  },
  {
    id: "folder-nodejs",
    title: "Node.js",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "folder-program-files",
    createdAt: Date.parse("2025-06-01T10:05:00"),
    sortOrder: 10,
  },
  {
    id: "folder-git",
    title: "Git",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "folder-program-files",
    createdAt: Date.parse("2025-06-01T10:10:00"),
    sortOrder: 11,
  },

  // ── C:\Program Files\JacobOS\ ────────────────────────────────────────────
  {
    id: "binary-jacobos-exe",
    title: "jacobos.exe",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-jacobos-app",
    createdAt: Date.parse("2026-03-13T12:00:00"),
    sortOrder: 8,
  },
  {
    id: "binary-jacobos-dll",
    title: "jacobos-shell.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-jacobos-app",
    createdAt: Date.parse("2026-03-13T12:00:00"),
    sortOrder: 9,
  },
  {
    id: "text-app-config",
    title: "app.config",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-jacobos-app",
    createdAt: Date.parse("2026-01-10T09:10:00"),
    sortOrder: 10,
    content:
      "[JacobOS]\nVersion=1.0.0\nBuild=2026-03-13\nAuthor=Jacob Rushinski\nEnvironment=production\n\n[Shell]\nDesktopColor=#008080\nIconSize=normal\nClockFormat=12h\nBootAnimationEnabled=true\n\n[Network]\nContactAPI=https://jacobrushinski.dev/api/contact\nResumeURL=https://jacobrushinski.dev/resume.pdf",
  },
  {
    id: "text-changelog",
    title: "changelog.txt",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-jacobos-app",
    createdAt: Date.parse("2026-03-13T12:00:00"),
    sortOrder: 11,
    content:
      "JacobOS — Changelog\n\nv1.0.0  (2026-03-13)\n  + Initial release\n  + Window manager: drag, resize, z-index, minimize, maximize\n  + File Explorer with tree navigation and virtual filesystem\n  + Recycle Bin: delete, restore, empty\n  + Terminal with command interpreter\n  + Calculator, Minesweeper, Help, Settings\n  + About, Skills, Experience, Projects, Videos, Contact, Location apps\n  + Win95-style scrollbars, context menus, dialogs\n  + Boot animation sequence\n  + Alt+Tab switcher\n\nv0.9.0  (2026-02-01)\n  + Beta build — core window manager\n  + Initial app stubs\n\nv0.1.0  (2026-01-10)\n  + Project scaffolded",
  },
  {
    id: "binary-assets-dll",
    title: "assets.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-jacobos-app",
    createdAt: Date.parse("2026-03-13T12:00:00"),
    sortOrder: 12,
  },

  // ── C:\Program Files\Visual Studio Code\ ────────────────────────────────
  {
    id: "binary-code-exe",
    title: "code.exe",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-vscode",
    createdAt: Date.parse("2025-06-01T10:00:00"),
    sortOrder: 10,
  },
  {
    id: "text-vscode-settings",
    title: "settings.json",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-vscode",
    createdAt: Date.parse("2025-09-01T09:00:00"),
    sortOrder: 11,
    content:
      '{\n  "editor.fontSize": 14,\n  "editor.tabSize": 2,\n  "editor.formatOnSave": true,\n  "editor.defaultFormatter": "esbenp.prettier-vscode",\n  "editor.fontFamily": "JetBrains Mono, Fira Code, monospace",\n  "workbench.colorTheme": "One Dark Pro",\n  "terminal.integrated.shell.windows": "C:\\\\Windows\\\\System32\\\\cmd.exe",\n  "files.autoSave": "onFocusChange",\n  "prettier.singleQuote": false,\n  "prettier.semi": true\n}',
  },
  {
    id: "binary-vscode-dll",
    title: "electron.dll",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-vscode",
    createdAt: Date.parse("2025-06-01T10:00:00"),
    sortOrder: 20,
  },

  // ── C:\Program Files\Node.js\ ────────────────────────────────────────────
  {
    id: "binary-node-exe",
    title: "node.exe",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-nodejs",
    createdAt: Date.parse("2025-06-01T10:05:00"),
    sortOrder: 10,
  },
  {
    id: "text-npmrc",
    title: ".npmrc",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-nodejs",
    createdAt: Date.parse("2025-06-01T10:05:00"),
    sortOrder: 11,
    content:
      "registry=https://registry.npmjs.org/\nsave-exact=false\npackage-lock=true\nengine-strict=false",
  },

  // ── C:\Program Files\Git\ ────────────────────────────────────────────────
  {
    id: "binary-git-exe",
    title: "git.exe",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-git",
    createdAt: Date.parse("2025-06-01T10:10:00"),
    sortOrder: 10,
  },
  {
    id: "text-gitconfig",
    title: ".gitconfig",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-git",
    createdAt: Date.parse("2025-06-01T10:10:00"),
    sortOrder: 11,
    content:
      "[user]\n  name = Jacob Rushinski\n  email = jacob@jacobrushinski.dev\n\n[core]\n  autocrlf = input\n  editor = code --wait\n\n[alias]\n  st = status\n  co = checkout\n  br = branch\n  lg = log --oneline --graph --decorate\n  undo = reset HEAD~1 --mixed\n\n[push]\n  default = simple",
  },

  // ════════════════════════════════════════════════════════════════════════════
  // C:\Users\
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: "folder-jacob",
    title: "Jacob",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "folder-users",
    createdAt: Date.parse("2026-01-10T08:10:00"),
    sortOrder: 8,
  },

  // ── C:\Users\Jacob\ ──────────────────────────────────────────────────────
  {
    id: "folder-documents",
    title: "Documents",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "folder-jacob",
    createdAt: Date.parse("2026-01-10T08:30:00"),
    sortOrder: 8,
  },
  {
    id: "folder-downloads",
    title: "Downloads",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "folder-jacob",
    createdAt: Date.parse("2026-01-10T08:40:00"),
    sortOrder: 9,
  },
  {
    id: "folder-desktop-user",
    title: "Desktop",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "folder-jacob",
    createdAt: Date.parse("2026-01-10T08:45:00"),
    sortOrder: 10,
  },
  {
    id: "text-user-env",
    title: ".env",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-jacob",
    createdAt: Date.parse("2026-01-10T09:00:00"),
    sortOrder: 20,
    content:
      "# User environment variables\nUSERNAME=jacob\nHOME=C:\\Users\\Jacob\nPATH=C:\\Windows\\System32;C:\\Program Files\\Git;C:\\Program Files\\Node.js;C:\\Program Files\\JacobOS\nNODE_ENV=development\nEDITOR=code",
  },

  // ── C:\Users\Jacob\Documents\ ────────────────────────────────────────────
  {
    id: "folder-school",
    title: "Thaddeus Stevens",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "folder-documents",
    createdAt: Date.parse("2025-09-01T09:00:00"),
    sortOrder: 8,
  },
  {
    id: "folder-work",
    title: "Giant Food Stores",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "folder-documents",
    createdAt: Date.parse("2024-06-10T08:00:00"),
    sortOrder: 9,
  },
  {
    id: "binary-resume",
    title: "resume.pdf",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-documents",
    createdAt: Date.parse("2026-03-01T10:00:00"),
    sortOrder: 10,
  },
  {
    id: "text-bio",
    title: "bio-draft.txt",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-documents",
    createdAt: Date.parse("2026-02-01T11:00:00"),
    sortOrder: 11,
    content:
      "Jacob Rushinski — Bio Draft\n\nComputer Science student at Thaddeus Stevens College of Technology (Lancaster, PA).\nCurrently working at Giant Food Stores in the Harrisburg area.\nSpend weekends in Philadelphia — planning to move there after graduation.\n\nBuilding JacobOS as both a portfolio and a genuine passion project.\nInterested in full-stack web development, systems programming, and clean UI.\n\nLooking for software development roles in the Philadelphia area or remote.",
  },
  {
    id: "text-cover-letter",
    title: "cover-letter.txt",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-documents",
    createdAt: Date.parse("2026-03-01T09:30:00"),
    sortOrder: 12,
    content:
      "Dear Hiring Manager,\n\nI am a Computer Science student at Thaddeus Stevens College of Technology, graduating Spring 2026, seeking a software development role in the Philadelphia area.\n\nI built JacobOS — this portfolio — from scratch using Next.js, React, and a hand-crafted Win95 component system. It demonstrates my ability to design and implement complex UI systems, manage application state, and ship polished, production-ready code.\n\nI also have practical experience from my time at Giant Food Stores: prioritization under pressure, process optimization, and clear communication — skills that translate directly to engineering work.\n\nMy resume and full project list are at jacobrushinski.dev.\n\nSincerely,\nJacob Rushinski",
  },
  {
    id: "binary-references",
    title: "references.docx",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-documents",
    createdAt: Date.parse("2026-03-01T10:05:00"),
    sortOrder: 13,
  },

  // ── C:\Users\Jacob\Documents\Thaddeus Stevens\ ───────────────────────────
  {
    id: "text-schedule",
    title: "spring-2026-schedule.txt",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-school",
    createdAt: Date.parse("2026-01-13T08:00:00"),
    sortOrder: 10,
    content:
      "Spring 2026 — Thaddeus Stevens College of Technology\n\nMON  09:00  CSCI 472  Software Engineering\nMON  11:00  CSCI 450  Database Systems\nTUE  10:00  CSCI 461  Operating Systems\nWED  09:00  CSCI 472  (Lab)\nWED  13:00  CSCI 480  Web Development\nTHU  10:00  CSCI 461  (Lab)\nFRI  11:00  CSCI 499  Senior Project Capstone\n\nCampus: Lancaster, PA\nCommute from Harrisburg: ~30 min via Route 30",
  },
  {
    id: "text-os-notes",
    title: "csci461-notes.txt",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-school",
    createdAt: Date.parse("2026-02-18T10:30:00"),
    sortOrder: 11,
    content:
      "CSCI 461 — Operating Systems\nProcess Scheduling Notes\n\nAlgorithms covered:\n  FCFS   — First Come First Served\n  SJN    — Shortest Job Next\n  RR     — Round Robin (quantum = 4ms)\n  PRI    — Priority Scheduling (preemptive)\n\nMemory management:\n  Paging, segmentation, virtual memory\n  Page replacement: LRU, FIFO, Optimal\n\nNote: Building JacobOS simultaneously — applying these concepts directly.",
  },
  {
    id: "binary-capstone",
    title: "capstone-proposal.pdf",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-school",
    createdAt: Date.parse("2026-02-10T14:00:00"),
    sortOrder: 12,
  },
  {
    id: "binary-db-assignment",
    title: "csci450-assignment3.pdf",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-school",
    createdAt: Date.parse("2026-03-05T10:00:00"),
    sortOrder: 13,
  },

  // ── C:\Users\Jacob\Documents\Giant Food Stores\ ──────────────────────────
  {
    id: "text-work-schedule",
    title: "march-schedule.txt",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-work",
    createdAt: Date.parse("2026-03-01T07:00:00"),
    sortOrder: 10,
    content:
      "Giant Food Stores — March 2026\nLocation: Harrisburg, PA\n\n03  Mon   3:00pm – 9:00pm\n05  Wed   4:00pm – 10:00pm\n08  Sat  10:00am – 6:00pm\n10  Mon   3:00pm – 9:00pm\n12  Wed   4:00pm – 10:00pm\n15  Sat  10:00am – 6:00pm\n17  Mon   3:00pm – 9:00pm\n19  Wed   4:00pm – 10:00pm\n22  Sat  10:00am – 6:00pm\n\nNote: School Mon–Fri Lancaster; work evenings + weekends Harrisburg.",
  },
  {
    id: "binary-onboarding",
    title: "onboarding-packet.pdf",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-work",
    createdAt: Date.parse("2024-06-10T09:00:00"),
    sortOrder: 11,
  },

  // ── C:\Users\Jacob\Downloads\ ────────────────────────────────────────────
  {
    id: "binary-nextjs-docs",
    title: "nextjs-15-docs.pdf",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-downloads",
    createdAt: Date.parse("2026-02-10T16:00:00"),
    sortOrder: 10,
  },
  {
    id: "binary-tailwind-guide",
    title: "tailwind-v4-guide.pdf",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-downloads",
    createdAt: Date.parse("2026-01-20T14:00:00"),
    sortOrder: 11,
  },
  {
    id: "binary-septa-map",
    title: "septa-transit-map.pdf",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-downloads",
    createdAt: Date.parse("2025-11-15T10:00:00"),
    sortOrder: 12,
  },
  {
    id: "binary-figma-kit",
    title: "win95-ui-kit.zip",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-downloads",
    createdAt: Date.parse("2026-01-08T20:00:00"),
    sortOrder: 13,
  },

  // ── C:\Users\Jacob\Desktop\ ──────────────────────────────────────────────
  {
    id: "text-desktop-notes",
    title: "notes.txt",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-desktop-user",
    createdAt: Date.parse("2026-03-10T20:00:00"),
    sortOrder: 10,
    content:
      "Quick Notes\n\nTODO before launch:\n  [x] Finish Location app\n  [x] Polish Contact form\n  [x] Fix window restore sizing\n  [ ] Deploy to jacobrushinski.dev\n  [ ] Submit portfolio to job applications\n\nInterview prep:\n  - Review system design basics\n  - Practice React hooks questions\n  - Leetcode: medium array/string problems",
  },

  // ════════════════════════════════════════════════════════════════════════════
  // C:\Projects\
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: "folder-jacobos",
    title: "jacobos-portfolio",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "folder-projects",
    createdAt: Date.parse("2026-01-10T08:50:00"),
    sortOrder: 8,
  },
  {
    id: "folder-old-projects",
    title: "archive",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "folder-projects",
    createdAt: Date.parse("2025-06-01T10:00:00"),
    sortOrder: 9,
  },

  // ── C:\Projects\jacobos-portfolio\ ──────────────────────────────────────
  {
    id: "text-package-json",
    title: "package.json",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-jacobos",
    createdAt: Date.parse("2026-01-10T09:00:00"),
    sortOrder: 8,
    content:
      '{\n  "name": "jacobos-portfolio",\n  "version": "1.0.0",\n  "private": true,\n  "scripts": {\n    "dev": "next dev",\n    "build": "next build",\n    "start": "next start",\n    "lint": "next lint"\n  },\n  "dependencies": {\n    "next": "^15.0.0",\n    "react": "^18.3.0",\n    "react-dom": "^18.3.0",\n    "react-simple-maps": "^3.0.0"\n  },\n  "devDependencies": {\n    "eslint": "^8.57.0",\n    "tailwindcss": "^3.4.0"\n  }\n}',
  },
  {
    id: "text-project-readme",
    title: "README.txt",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-jacobos",
    createdAt: Date.parse("2026-01-10T09:05:00"),
    sortOrder: 9,
    content:
      "jacobos-portfolio\n\nAn interactive portfolio built as a Windows 95-style desktop OS.\nBuilt with Next.js 15, React 18, and a fully hand-crafted Win95 component system.\n\nFeatures:\n  - Window manager with drag, resize, minimize, maximize\n  - File Explorer with virtual filesystem\n  - 12+ apps: About, Skills, Experience, Projects, Videos, Contact,\n    Terminal, Calculator, Settings, Location, Help, Minesweeper\n  - Recycle Bin, context menus, keyboard shortcuts\n  - Win95-style scrollbars, dialogs, and boot animation\n\nRunning locally:\n  npm install\n  npm run dev\n  Open http://localhost:3000",
  },
  {
    id: "text-env-example",
    title: ".env.example",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-jacobos",
    createdAt: Date.parse("2026-01-10T09:10:00"),
    sortOrder: 10,
    content:
      "# Contact form email service\nRESEND_API_KEY=\nCONTACT_TO_EMAIL=\n\n# Site metadata\nNEXT_PUBLIC_SITE_URL=https://jacobrushinski.dev",
  },
  {
    id: "text-todo",
    title: "todo.txt",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-jacobos",
    createdAt: Date.parse("2026-01-14T16:05:00"),
    sortOrder: 11,
    content:
      "jacobos-portfolio — TODO\n\n[x] Boot sequence animation\n[x] Window manager (drag, resize, z-index)\n[x] File Explorer with virtual filesystem\n[x] Recycle Bin\n[x] Terminal\n[x] Calculator, Help, Minesweeper\n[x] Win95 scrollbars\n[x] Location app with live map\n[x] Alt+Tab window switcher\n[ ] Deploy to jacobrushinski.dev\n[ ] Connect contact form to email service\n[ ] Mobile responsive improvements",
  },
  {
    id: "binary-package-lock",
    title: "package-lock.json",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-jacobos",
    createdAt: Date.parse("2026-01-10T09:00:00"),
    sortOrder: 20,
  },
  {
    id: "binary-next-config",
    title: "next.config.mjs",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-jacobos",
    createdAt: Date.parse("2026-01-10T09:00:00"),
    sortOrder: 21,
  },

  // ── C:\Projects\archive\ ─────────────────────────────────────────────────
  {
    id: "text-archive-index",
    title: "index.txt",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-old-projects",
    createdAt: Date.parse("2025-06-01T10:30:00"),
    sortOrder: 10,
    content:
      "Projects Archive\n\npersonal-site-v1/\n  Plain HTML/CSS. First web project. ~2023.\n\ntodo-app-react/\n  Basic React todo list. Classic beginner project.\n\nweather-widget/\n  Fetched from OpenWeather API. JavaScript practice.\n\ndiscord-bot/\n  Node.js bot for a gaming server. Had a music player.\n\ncalculator-v1/\n  Vanilla JS calculator. Now replaced by the Win95 version in JacobOS.",
  },
  {
    id: "binary-site-v1",
    title: "personal-site-v1.zip",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-old-projects",
    createdAt: Date.parse("2023-12-01T10:00:00"),
    sortOrder: 11,
  },
  {
    id: "binary-discord-bot",
    title: "discord-bot.zip",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-old-projects",
    createdAt: Date.parse("2024-08-01T10:00:00"),
    sortOrder: 12,
  },

  // ════════════════════════════════════════════════════════════════════════════
  // C:\Temp\
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: "binary-tmp1",
    title: "~DF3A12.tmp",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-temp",
    createdAt: Date.parse("2026-03-13T11:58:00"),
    sortOrder: 10,
  },
  {
    id: "binary-tmp2",
    title: "~build-cache.tmp",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-temp",
    createdAt: Date.parse("2026-03-13T11:59:00"),
    sortOrder: 11,
  },
  {
    id: "binary-tmp3",
    title: "next-build-5f8a.tmp",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-temp",
    createdAt: Date.parse("2026-03-13T12:00:00"),
    sortOrder: 12,
  },

  // ════════════════════════════════════════════════════════════════════════════
  // D:\ — Backups & storage
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: "folder-archive",
    title: "Backups",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "drive-d",
    createdAt: Date.parse("2026-01-10T08:45:00"),
    sortOrder: 10,
  },
  {
    id: "folder-media",
    title: "Media",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "drive-d",
    createdAt: Date.parse("2025-01-01T10:00:00"),
    sortOrder: 11,
  },

  // ── D:\Backups\ ──────────────────────────────────────────────────────────
  {
    id: "text-backup-log",
    title: "backup-log.txt",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-archive",
    createdAt: Date.parse("2026-01-15T09:25:00"),
    sortOrder: 10,
    content:
      "Backup Log — D:\\Backups\n\n[2026-01-10]  Initial snapshot — C: drive baseline\n[2026-01-14]  Projects folder added\n[2026-02-01]  Documents synced\n[2026-03-01]  Pre-launch full backup\n[2026-03-13]  v1.0 release snapshot — verified OK\n\nNext scheduled: 2026-04-01\nStorage used: 4.2 GB of 500 GB",
  },
  {
    id: "binary-c-backup",
    title: "C-drive-2026-03-13.zip",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-archive",
    createdAt: Date.parse("2026-03-13T13:00:00"),
    sortOrder: 11,
  },
  {
    id: "binary-projects-backup",
    title: "projects-backup-2026-03.zip",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-archive",
    createdAt: Date.parse("2026-03-01T09:00:00"),
    sortOrder: 12,
  },

  // ── D:\Media\ ────────────────────────────────────────────────────────────
  {
    id: "binary-vid1",
    title: "project-demo-v1.mp4",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-media",
    createdAt: Date.parse("2026-02-20T18:00:00"),
    sortOrder: 10,
  },
  {
    id: "binary-vid2",
    title: "jacobos-walkthrough.mp4",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-media",
    createdAt: Date.parse("2026-03-12T20:00:00"),
    sortOrder: 11,
  },
  {
    id: "binary-headshot",
    title: "headshot-2025.jpg",
    glyph: Icons.file,
    windowId: null,
    itemType: "binary",
    system: false,
    parentId: "folder-media",
    createdAt: Date.parse("2025-09-15T14:00:00"),
    sortOrder: 12,
  },

];
