"use client";

export const INITIAL_ICON_POSITIONS = {
  // Column 1
  about: { x: 12, y: 8 },
  skills: { x: 12, y: 134 },
  experience: { x: 12, y: 260 },
  projects: { x: 12, y: 386 },
  contact: { x: 12, y: 512 },
  // Column 2
  welcome: { x: 120, y: 8 },
  resume: { x: 120, y: 134 },
  location: { x: 120, y: 260 },
  videos: { x: 120, y: 386 },
  help: { x: 120, y: 512 },
  // Column 3
  settings: { x: 228, y: 8 },
  explorer: { x: 228, y: 134 },
  terminal: { x: 228, y: 260 },
  trash: { x: 228, y: 386 },
  minesweeper: { x: 228, y: 512 },
};

export const INITIAL_WINDOWS = {
  welcome: {
    id: "welcome",
    title: "Welcome",
    x: 220,
    y: 56,
    w: 750,
    h: 480,
    isOpen: true,
    isMinimized: false,
    isMaximized: false,
    z: 11,
  },
  about: {
    id: "about",
    title: "About",
    x: 72,
    y: 44,
    w: 1150,
    h: 560,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    z: 10,
  },
  skills: {
    id: "skills",
    title: "Skills",
    x: 132,
    y: 68,
    w: 1150,
    h: 650,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    z: 9,
  },
  experience: {
    id: "experience",
    title: "Experience",
    x: 188,
    y: 82,
    w: 720,
    h: 500,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    z: 8,
  },
  projects: {
    id: "projects",
    title: "Projects",
    x: 156,
    y: 60,
    w: 820,
    h: 560,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    z: 7,
  },
  videos: {
    id: "videos",
    title: "Videos",
    x: 140,
    y: 52,
    w: 920,
    h: 580,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    z: 7,
  },
  contact: {
    id: "contact",
    title: "Contact",
    x: 292,
    y: 92,
    w: 460,
    h: 420,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    z: 5,
  },
  location: {
    id: "location",
    title: "Where's Jacob",
    x: 140,
    y: 40,
    w: 800,
    h: 660,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    z: 5,
  },
  terminal: {
    id: "terminal",
    title: "Terminal",
    x: 124,
    y: 92,
    w: 640,
    h: 400,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    z: 4,
  },
  trash: {
    id: "trash",
    title: "Recycle Bin",
    x: 320,
    y: 100,
    w: 650,
    h: 450,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    z: 3,
  },
  explorer: {
    id: "explorer",
    title: "File Explorer",
    x: 148,
    y: 66,
    w: 860,
    h: 540,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    z: 2,
  },
  settings: {
    id: "settings",
    title: "Settings",
    x: 214,
    y: 88,
    w: 700,
    h: 520,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    z: 1,
  },
  textdoc: {
    id: "textdoc",
    title: "Text Document",
    x: 248,
    y: 100,
    w: 560,
    h: 380,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    z: 12,
  },
  resume: {
    id: "resume",
    title: "Resume",
    x: 112,
    y: 44,
    w: 900,
    h: 620,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    z: 0,
  },
  minesweeper: {
    id: "minesweeper",
    title: "Minesweeper",
    x: 200,
    y: 80,
    w: 260,
    h: 360,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    z: 0,
  },
  help: {
    id: "help",
    title: "JacobOS Help",
    x: 160,
    y: 60,
    w: 600,
    h: 470,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    z: 0,
  },
};
