"use client";

import { Icons } from "./icons";

export const GRID = 1;
export const snap = (n) => Math.round(n / GRID) * GRID;
export const clamp = (val, min, max) => Math.max(min, Math.min(max, val));

export const ICON_VIEW_MODES = {
  small: { tileW: 68, tileH: 80, glyphScale: 0.85, labelSize: 10, cellX: 78, cellY: 94, maxLabel: 72 },
  medium: { tileW: 76, tileH: 90, glyphScale: 1, labelSize: 11, cellX: 90, cellY: 102, maxLabel: 84 },
  large: { tileW: 94, tileH: 112, glyphScale: 1.2, labelSize: 12, cellX: 108, cellY: 126, maxLabel: 100 },
};

export const MENU_TEXT_COLOR = "#162133";
export const DRAG_ITEM_MIME = "application/x-jacobos-item-id";
export const FULLSCREEN_WINDOW_IDS = new Set(["experience", "projects", "videos", "contact", "resume"]);
export const DEFAULT_PINNED_TASKBAR_IDS = ["about", "skills", "experience", "projects", "contact"];
export const DEFAULT_SETTINGS = {
  clockFormat: "12h",
  desktopColor: null,
  iconSizeMode: "medium",
  wallpaperPattern: "solid",
  crtEffectEnabled: true,
  masterSoundEnabled: true,
  uiSoundsEnabled: true,
  startupSoundEnabled: true,
  screensaverType: "none",
  screensaverTimeout: 120,
};
export const DEFAULT_EXPLORER_STATE = {
  currentFolderId: null,
  navStack: [],
  forwardStack: [],
  viewMode: "list",
  sidebarWidth: 180,
  searchQuery: "",
  selectedItemId: null,
};
export const WALLPAPER_PATTERNS = [
  { id: "solid", label: "Solid Color" },
  { id: "scanline", label: "Scanline Overlay" },
  { id: "dot-grid", label: "Dot Grid" },
  { id: "retro-stripe", label: "Retro Stripe" },
];
export const WALLPAPER_PATTERN_BACKGROUNDS = {
  solid: "none",
  scanline: "repeating-linear-gradient(180deg, rgba(255,255,255,0.08) 0px, rgba(255,255,255,0.08) 1px, transparent 1px, transparent 4px)",
  "dot-grid": "radial-gradient(rgba(255,255,255,0.18) 1px, transparent 1px)",
  "retro-stripe": "repeating-linear-gradient(135deg, rgba(255,255,255,0.15) 0 6px, transparent 6px 14px)",
};
export const SCREENSAVER_OPTIONS = [
  { id: "none", label: "None" },
  { id: "mystify", label: "Mystify" },
  { id: "bouncing-logo", label: "Bouncing Logo" },
  { id: "pipes", label: "Pipes" },
];
export const SCREENSAVER_TIMEOUT_OPTIONS = [
  { value: 60, label: "1 min" },
  { value: 120, label: "2 min" },
  { value: 300, label: "5 min" },
  { value: null, label: "Never" },
];
export const SYSTEM_SPECS = [
  ["Processor", "Jacob's Brain(TM) @ 3.52 GHz"],
  ["RAM", "16GB Determination"],
  ["Storage", "500GB of Side Projects"],
  ["OS", "JacobOS v1.0 (Build 2026)"],
  ["User", "jacob_rushinski"],
];
export const FILE_TYPE_LABELS = {
  app: "Application",
  computer: "Computer",
  drive: "Disk Drive",
  folder: "Folder",
  text: "Text Document",
  pdf: "PDF Document",
};
export const FILE_SIZE_LABELS = {
  app: "1.2 MB",
  computer: "",
  drive: "1.99 GB",
  folder: "0 bytes",
  text: "4 KB",
  pdf: "2.4 MB",
};

export const DESKTOP_COLORS = [
  { label: "Default", value: null, preview: "linear-gradient(180deg, #0b4aa6, #0a3f90)" },
  { label: "Teal", value: "#008080", preview: "#008080" },
  { label: "Navy", value: "#000080", preview: "#000080" },
  { label: "Forest", value: "#1a5c1a", preview: "#1a5c1a" },
  { label: "Maroon", value: "#800000", preview: "#800000" },
  { label: "Purple", value: "#4b0082", preview: "#4b0082" },
  { label: "Dark Gray", value: "#404040", preview: "#404040" },
  { label: "Black", value: "#000000", preview: "#000000" },
];

export const INITIAL_ICON_POSITIONS = {
  welcome: { x: 12, y: 8 },
  about: { x: 12, y: 104 },
  skills: { x: 12, y: 200 },
  experience: { x: 12, y: 296 },
  projects: { x: 12, y: 392 },
  videos: { x: 112, y: 296 },
  github: { x: 12, y: 488 },
  contact: { x: 12, y: 584 },
  terminal: { x: 12, y: 680 },
  trash: { x: 112, y: 680 },
  explorer: { x: 112, y: 8 },
  settings: { x: 112, y: 104 },
  location: { x: 112, y: 200 },
  resume: { x: 112, y: 392 },
};

export const INITIAL_WINDOWS = {
  welcome: { id: "welcome", title: "Welcome", x: 250, y: 95, w: 800, h: 500, isOpen: true, isMinimized: false, isMaximized: false, z: 11 },
  about: { id: "about", title: "About", x: 30, y: 20, w: 1200, h: 600, isOpen: false, isMinimized: false, isMaximized: false, z: 10 },
  skills: { id: "skills", title: "Skills", x: 180, y: 50, w: 950, h: 550, isOpen: false, isMinimized: false, isMaximized: false, z: 9 },
  experience: { id: "experience", title: "Experience", x: 180, y: 50, w: 560, h: 480, isOpen: false, isMinimized: false, isMaximized: false, z: 8 },
  projects: { id: "projects", title: "Projects", x: 100, y: 20, w: 600, h: 560, isOpen: false, isMinimized: false, isMaximized: false, z: 7 },
  videos: { id: "videos", title: "Videos", x: 140, y: 40, w: 840, h: 560, isOpen: false, isMinimized: false, isMaximized: false, z: 7 },
  contact: { id: "contact", title: "Contact", x: 260, y: 80, w: 400, h: 380, isOpen: false, isMinimized: false, isMaximized: false, z: 5 },
  location: { id: "location", title: "Jacobs Time", x: 280, y: 110, w: 560, h: 300, isOpen: false, isMinimized: false, isMaximized: false, z: 5 },
  terminal: { id: "terminal", title: "Terminal", x: 120, y: 50, w: 500, h: 350, isOpen: false, isMinimized: false, isMaximized: false, z: 4 },
  trash: { id: "trash", title: "Recycle Bin", x: 300, y: 100, w: 320, h: 260, isOpen: false, isMinimized: false, isMaximized: false, z: 3 },
  explorer: { id: "explorer", title: "File Explorer", x: 180, y: 64, w: 660, h: 430, isOpen: false, isMinimized: false, isMaximized: false, z: 2 },
  settings: { id: "settings", title: "Settings", x: 220, y: 76, w: 600, h: 460, isOpen: false, isMinimized: false, isMaximized: false, z: 1 },
  textdoc: { id: "textdoc", title: "Text Document", x: 240, y: 80, w: 520, h: 360, isOpen: false, isMinimized: false, isMaximized: false, z: 12 },
  resume: { id: "resume", title: "Resume.pdf", x: 80, y: 30, w: 760, h: 600, isOpen: false, isMinimized: false, isMaximized: false, z: 0 },
};

export const canPinItemToTaskbar = (item) => item?.itemType === "app" && !!item.windowId;

export const snapIconToGrid = (x, y, mode = "medium", marginX = 12, marginY = 8) => {
  const grid = ICON_VIEW_MODES[mode] || ICON_VIEW_MODES.medium;
  const gx = Math.round((x - marginX) / grid.cellX);
  const gy = Math.round((y - marginY) / grid.cellY);
  return {
    x: marginX + gx * grid.cellX,
    y: marginY + gy * grid.cellY,
  };
};

const SYSTEM_DESKTOP_ICON_DEFS = [
  { id: "welcome", title: "Welcome", glyph: Icons.welcome, windowId: "welcome", itemType: "app", system: true, parentId: null },
  { id: "about", title: "About", glyph: Icons.about, windowId: "about", itemType: "app", system: true, parentId: null },
  { id: "skills", title: "Skills", glyph: Icons.skills, windowId: "skills", itemType: "app", system: true, parentId: null },
  { id: "experience", title: "Experience", glyph: Icons.experience, windowId: "experience", itemType: "app", system: true, parentId: null },
  { id: "projects", title: "Projects", glyph: Icons.projects, windowId: "projects", itemType: "app", system: true, parentId: null },
  { id: "videos", title: "Videos", glyph: Icons.videos, windowId: "videos", itemType: "app", system: true, parentId: null },
  { id: "contact", title: "Contact", glyph: Icons.contact, windowId: "contact", itemType: "app", system: true, parentId: null },
  { id: "location", title: "Jacobs Time", glyph: Icons.location, windowId: "location", itemType: "app", system: true, parentId: null },
  { id: "terminal", title: "Terminal", glyph: Icons.terminal, windowId: "terminal", itemType: "app", system: true, parentId: null },
  { id: "explorer", title: "File Explorer", glyph: Icons.folder, windowId: "explorer", itemType: "app", system: true, parentId: null },
  { id: "settings", title: "Settings", glyph: Icons.settings, windowId: "settings", itemType: "app", system: true, parentId: null },
  { id: "trash", title: "Recycle Bin", glyph: Icons.trashEmpty, windowId: "trash", itemType: "app", system: true, parentId: null },
  { id: "resume", title: "Resume.pdf", glyph: Icons.resume, windowId: "resume", itemType: "app", system: true, parentId: null },
];

export const buildSystemDesktopIcons = (renamedSystemIcons = {}, options = {}) =>
  SYSTEM_DESKTOP_ICON_DEFS.map((item) => ({
    ...item,
    glyph: item.id === "trash" ? (options.recycleBinHasItems ? Icons.trashFull : Icons.trashEmpty) : item.glyph,
    title: renamedSystemIcons[item.id] || item.title,
    sizeLabel: FILE_SIZE_LABELS[item.itemType] || "0 bytes",
    typeLabel: FILE_TYPE_LABELS[item.itemType] || "Item",
  }));

const EXPLORER_SYSTEM_ITEM_DEFS = [
  {
    id: "my-computer",
    title: "My Computer",
    glyph: Icons.computer,
    windowId: "explorer",
    itemType: "computer",
    system: true,
    explorerOnly: true,
    isContainer: true,
    readOnly: true,
    parentId: null,
    sortOrder: 0,
    typeLabel: "Computer",
    sizeLabel: "",
  },
  {
    id: "drive-a",
    title: "3 1/2 Floppy (A:)",
    glyph: Icons.drive,
    windowId: "explorer",
    itemType: "drive",
    system: true,
    explorerOnly: true,
    isContainer: true,
    parentId: "my-computer",
    sortOrder: 0,
    typeLabel: "Floppy Disk",
    sizeLabel: "1.44 MB",
  },
  {
    id: "drive-c",
    title: "JacobOS (C:)",
    glyph: Icons.drive,
    windowId: "explorer",
    itemType: "drive",
    system: true,
    explorerOnly: true,
    isContainer: true,
    parentId: "my-computer",
    sortOrder: 1,
    typeLabel: "Local Disk",
    sizeLabel: "2.1 GB",
  },
  {
    id: "drive-d",
    title: "Archive (D:)",
    glyph: Icons.drive,
    windowId: "explorer",
    itemType: "drive",
    system: true,
    explorerOnly: true,
    isContainer: true,
    parentId: "my-computer",
    sortOrder: 2,
    typeLabel: "Local Disk",
    sizeLabel: "824 MB",
  },
  {
    id: "control-panel",
    title: "Control Panel",
    glyph: Icons.settings,
    windowId: "settings",
    itemType: "app",
    system: true,
    explorerOnly: true,
    parentId: "my-computer",
    sortOrder: 3,
    typeLabel: "System Folder",
    sizeLabel: "",
  },
];

export const buildExplorerSystemItems = () => EXPLORER_SYSTEM_ITEM_DEFS.map((item) => ({ ...item }));

export const INITIAL_CUSTOM_ITEMS = [
  {
    id: "folder-program-files",
    title: "Program Files",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "drive-c",
    createdAt: Date.parse("2026-01-10T08:22:00"),
    sortOrder: 8,
  },
  {
    id: "folder-windows",
    title: "Windows",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "drive-c",
    createdAt: Date.parse("2026-01-10T08:24:00"),
    sortOrder: 9,
  },
  {
    id: "folder-documents",
    title: "My Documents",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "drive-c",
    createdAt: Date.parse("2026-01-10T08:30:00"),
    sortOrder: 10,
  },
  {
    id: "folder-projects",
    title: "Projects",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "drive-c",
    createdAt: Date.parse("2026-01-10T08:35:00"),
    sortOrder: 11,
  },
  {
    id: "folder-downloads",
    title: "Downloads",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "drive-c",
    createdAt: Date.parse("2026-01-10T08:40:00"),
    sortOrder: 12,
  },
  {
    id: "folder-temp",
    title: "Temp",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "drive-c",
    createdAt: Date.parse("2026-01-10T08:42:00"),
    sortOrder: 13,
  },
  {
    id: "folder-archive",
    title: "Backups",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "drive-d",
    createdAt: Date.parse("2026-01-10T08:45:00"),
    sortOrder: 10,
  },
  {
    id: "folder-jacobos",
    title: "JacobOS",
    glyph: Icons.folder,
    windowId: "explorer",
    itemType: "folder",
    system: false,
    parentId: "folder-projects",
    createdAt: Date.parse("2026-01-10T08:50:00"),
    sortOrder: 10,
  },
  {
    id: "text-readme",
    title: "readme.txt",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "drive-c",
    createdAt: Date.parse("2026-01-10T08:55:00"),
    content: "JacobOS virtual drive initialized.\n\nUse File Explorer to browse, create folders, and move items around.",
    sortOrder: 20,
  },
  {
    id: "text-autoexec",
    title: "autoexec.bat",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "drive-c",
    createdAt: Date.parse("2026-01-10T09:00:00"),
    content: "@echo off\nprompt $p$g\npath C:\\WINDOWS;C:\\WINDOWS\\COMMAND",
    sortOrder: 21,
  },
  {
    id: "text-config",
    title: "config.sys",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "drive-c",
    createdAt: Date.parse("2026-01-10T09:03:00"),
    content: "FILES=40\nBUFFERS=30\nDOS=HIGH,UMB",
    sortOrder: 22,
  },
  {
    id: "text-launch-notes",
    title: "launch-notes.txt",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-documents",
    createdAt: Date.parse("2026-01-12T10:15:00"),
    content: "Boot sequence tuned.\nExplorer tree expanded.\nStill shipping more retro polish.",
    sortOrder: 20,
  },
  {
    id: "text-desktop-ini",
    title: "desktop.ini",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-documents",
    createdAt: Date.parse("2026-01-12T10:20:00"),
    content: "[.ShellClassInfo]\nIconResource=JacobOS.dll,3",
    sortOrder: 22,
  },
  {
    id: "pdf-resume-copy",
    title: "resume.pdf",
    glyph: Icons.resume,
    windowId: "resume",
    itemType: "pdf",
    system: false,
    parentId: "folder-documents",
    createdAt: Date.parse("2026-01-13T14:10:00"),
    sortOrder: 21,
  },
  {
    id: "text-release-notes",
    title: "release-notes.txt",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-projects",
    createdAt: Date.parse("2026-01-13T17:10:00"),
    content: "JacobOS roadmap\n\n- Boot CRT pass\n- Settings redesign\n- Explorer polish\n- Recycle Bin parity",
    sortOrder: 19,
  },
  {
    id: "text-todo",
    title: "todo.txt",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-jacobos",
    createdAt: Date.parse("2026-01-14T16:05:00"),
    content: "1. Settings overhaul\n2. Explorer context menus\n3. Recycle Bin restore flow",
    sortOrder: 20,
  },
  {
    id: "text-system-log",
    title: "system.log",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-windows",
    createdAt: Date.parse("2026-01-14T08:45:00"),
    content: "Boot sequence initialized.\nExplorer shell online.\nNo fatal errors detected.",
    sortOrder: 18,
  },
  {
    id: "text-install-notes",
    title: "install.txt",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-program-files",
    createdAt: Date.parse("2026-01-14T09:10:00"),
    content: "Installed applications:\n- JacobOS Shell\n- Portfolio Suite\n- Terminal Utilities",
    sortOrder: 18,
  },
  {
    id: "text-archive-log",
    title: "archive-log.txt",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "folder-archive",
    createdAt: Date.parse("2026-01-15T09:25:00"),
    content: "Backups verified.\nNo data loss detected.",
    sortOrder: 20,
  },
  {
    id: "text-floppy-note",
    title: "disk-note.txt",
    glyph: Icons.file,
    windowId: "textdoc",
    itemType: "text",
    system: false,
    parentId: "drive-a",
    createdAt: Date.parse("2026-01-15T09:40:00"),
    content: "3 1/2 inch diskette ready.\nRemember to back up your side projects.",
    sortOrder: 12,
  },
];
